[general_settings]
remind_before_launch_mins = 1500

# how many hours before launch until you add the launch in the begin day report
launch_report_hours = 96

refresh_time_seconds = 30

[email.before_launch_email]
send_before_launch_email = true

subject = "Launch Soon!"

email = """
A {provider} {vehicle} will launch in {remind_before_launch_mins} mins at pad {launch_pad}, {launch_site}.

Data by RocketLaunch.live
"""

[email.beginning_of_day_email]
send_beginning_of_day_email = true

# To prevent skipping sending the daily notification, do not set the send time a few minutes before or after midnight.
# To be safe, keep it 30 minutes away from midnight minimum.
send_time = 09:30:00

subject = "Upcoming Launch!"

email = """
A {provider} {vehicle} will launch at {launch_time} at pad {launch_pad} at {launch_site}.

Data by RocketLaunch.live
"""