# Must be a valid timezone from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones in the TZ identifier column
# All times, including the times in this config file, and the times in the daily report, are in this timezone
timezone = "America/New_York"

[refresh]
# How often the program should refresh and check whether it should send a reminder
refresh_seconds = 30

[exit]
# Whether the program should exit at the designated time
# When being hosted on a server, it is recommended for the program to exit at the given time to "reset" it in case anything goes awry
should_exit = true

# The time at which the program exits
# !!! Set this time to before reminders.daily.send_time to avoid sending the daily report twice !!!
exit_time = 04:00:00

[reminders.prelaunch]
# How many minutes before launch until the reminder is sent
# (e.g., if the launch is at 07:30, the reminder will send at 07:15 if this value is set to 15)
mins_before_launch = 15

subject = "Launch Soon!"

message = """
A {provider} {vehicle} will launch in {remind_before_launch_mins} mins on pad {launch_pad}, {launch_site}

Data by RocketLaunch.live
"""

[reminders.daily]
# How many hours before launch until you add it in the beginning of the day report
hours_before_launch = 24

# To prevent skipping sending the daily notification, do not set the send time a few minutes before or after midnight.
send_time = 09:30:00

subject = "Launch Today!"

message = """
A {provider} {vehicle} will launch at {launch_time} on pad {launch_pad}, {launch_site}

Data by RocketLaunch.live
"""