[general_settings]
remind_before_launch_mins = 15

# how many hours before launch until you add the launch in the beginning of the day report
launch_report_hours = 24

refresh_time_seconds = 30


# Whether the program should exit at the designated time
should_exit = true
# The time at which the program exits
# Set this to before reminder.daily.send_time to avoid sending the daily report twice
exit_time = 04:00:00

[reminders.prelaunch]
subject = "Launch Soon!"

message = """
A {provider} {vehicle} will launch in {remind_before_launch_mins} mins at pad {launch_pad}, {launch_site}

Data by RocketLaunch.live
"""

[reminders.daily]
# To prevent skipping sending the daily notification, do not set the send time a few minutes before or after midnight.
# To be safe, keep it 30 minutes away from midnight minimum.
send_time = 09:30:00

subject = "Launch Today!"

message = """
A {provider} {vehicle} will launch at {launch_time} at pad {launch_pad} at {launch_site}

Data by RocketLaunch.live
"""